on:
  issues:
    types: [opened]

jobs:
  issue_created:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/github-script@v6
        with:
          script: |
            const child_process = require('child_process');
            const body = context.payload.issue.body;
            const match = body.match(/https?:\/\/[^\s]+/);
            if (!match) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '🚫 No URL found in issue body.'
              });
              // Close the issue
              github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
              return;
            }
            const url = match[0];
            // Create directory named after the issue number
            const number = context.issue.number.toString();
            child_process.spawnSync('mkdir', [number]);
            // Run in that directory:
            const result = child_process.spawnSync('yt-dlp', ['--all-subs', '--skip-download', url], {
              cwd: number,
            });
            // Post the output as a comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '```\n' + result.stdout.toString() + '\n```'
            });
            // Close the issue
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
      - name: Show generated files
        run: find .
